[package]
name = "threadpool"
version = "0.1.0"
authors = ["GS-0834"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blocking_queue = { path = "../blocking_queue" }
